// Generated by npm run db:types from all migrations in PGlite. Do not edit.
// Tables are typed here; Relationships are omitted because adapters use explicit RPCs.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type Database = {
  public: {
    Tables: {
      game_events: {
        Row: {
          id: string;
          game_id: string;
          actor_id: string | null;
          request_id: string;
          event_type: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          actor_id?: string | null;
          request_id: string;
          event_type: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          actor_id?: string | null;
          request_id?: string;
          event_type?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      game_invites: {
        Row: {
          game_id: string;
          token_hash: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          game_id: string;
          token_hash: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          game_id?: string;
          token_hash?: string;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      games: {
        Row: {
          id: string;
          host_id: string;
          title: string;
          status: string;
          reveal_every: number;
          round_seconds: number;
          scoring_version: number;
          version: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          host_id: string;
          title: string;
          status?: string;
          reveal_every?: number;
          round_seconds?: number;
          scoring_version?: number;
          version?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          host_id?: string;
          title?: string;
          status?: string;
          reveal_every?: number;
          round_seconds?: number;
          scoring_version?: number;
          version?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      participants: {
        Row: {
          id: string;
          game_id: string;
          user_id: string;
          nickname: string;
          joined_at: string;
        };
        Insert: {
          id?: string;
          game_id: string;
          user_id: string;
          nickname: string;
          joined_at?: string;
        };
        Update: {
          id?: string;
          game_id?: string;
          user_id?: string;
          nickname?: string;
          joined_at?: string;
        };
        Relationships: [];
      };
      ratings: {
        Row: {
          id: string;
          game_id: string;
          round_id: string;
          participant_id: string;
          price_huf: number | null;
          alcohol_tenths: number;
          liking: number;
          submitted_at: string;
          price_bucket: number | null;
        };
        Insert: {
          id?: string;
          game_id: string;
          round_id: string;
          participant_id: string;
          price_huf?: number | null;
          alcohol_tenths: number;
          liking: number;
          submitted_at?: string;
          price_bucket?: number | null;
        };
        Update: {
          id?: string;
          game_id?: string;
          round_id?: string;
          participant_id?: string;
          price_huf?: number | null;
          alcohol_tenths?: number;
          liking?: number;
          submitted_at?: string;
          price_bucket?: number | null;
        };
        Relationships: [];
      };
      revealed_wines: {
        Row: {
          round_id: string;
          game_id: string;
          name: string;
          price_huf: number;
          alcohol_tenths: number;
          revealed_at: string;
        };
        Insert: {
          round_id: string;
          game_id: string;
          name: string;
          price_huf: number;
          alcohol_tenths: number;
          revealed_at?: string;
        };
        Update: {
          round_id?: string;
          game_id?: string;
          name?: string;
          price_huf?: number;
          alcohol_tenths?: number;
          revealed_at?: string;
        };
        Relationships: [];
      };
      rounds: {
        Row: {
          id: string;
          game_id: string;
          position: number;
          status: string;
          opened_at: string | null;
          closes_at: string | null;
          late_edits: boolean;
        };
        Insert: {
          id?: string;
          game_id: string;
          position: number;
          status?: string;
          opened_at?: string | null;
          closes_at?: string | null;
          late_edits?: boolean;
        };
        Update: {
          id?: string;
          game_id?: string;
          position?: number;
          status?: string;
          opened_at?: string | null;
          closes_at?: string | null;
          late_edits?: boolean;
        };
        Relationships: [];
      };
      wine_secrets: {
        Row: {
          round_id: string;
          game_id: string;
          name: string;
          price_huf: number;
          alcohol_tenths: number;
        };
        Insert: {
          round_id: string;
          game_id: string;
          name: string;
          price_huf: number;
          alcohol_tenths: number;
        };
        Update: {
          round_id?: string;
          game_id?: string;
          name?: string;
          price_huf?: number;
          alcohol_tenths?: number;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      allow_late_edits: { Args: { p_game_id: string; p_expected_version: number; p_request_id: string }; Returns: string };
      control_tasting: { Args: { p_game_id: string; p_expected_version: number; p_request_id: string; p_action: string; p_seconds?: number }; Returns: string };
      create_game: { Args: { p_request_id: string; p_title: string; p_round_seconds: number; p_reveal_every: number; p_wines: Json }; Returns: string };
      create_game_with_schedule: { Args: { p_request_id: string; p_title: string; p_round_seconds: number; p_reveal_every: number; p_wines: Json; p_steps: Json }; Returns: string };
      delete_game: { Args: { p_game_id: string; p_finalize?: boolean }; Returns: Json };
      get_game_results: { Args: { p_game_id: string }; Returns: Json };
      get_game_snapshot: { Args: { p_game_id: string }; Returns: Json };
      get_host_game: { Args: { p_game_id: string }; Returns: Json };
      get_lobby_snapshot: { Args: { p_game_id: string }; Returns: Json };
      get_tasting_schedule: { Args: { p_game_id: string }; Returns: Json };
      issue_invite: { Args: { p_game_id: string }; Returns: Json };
      join_game: { Args: { p_token: string; p_nickname?: string; p_reclaim?: string }; Returns: Json };
      list_host_games: { Args: Record<never, never>; Returns: Json };
      preview_invite: { Args: { p_token: string }; Returns: Json };
      resume_membership: { Args: { p_game_id: string; p_reclaim: string }; Returns: Json };
      save_tasting_schedule: { Args: { p_game_id: string; p_expected_version: number; p_request_id: string; p_steps: Json }; Returns: string };
      start_round: { Args: { p_game_id: string; p_expected_version: number; p_request_id: string }; Returns: string };
      submit_rating: { Args: { p_round_id: string; p_price_bucket: number; p_alcohol_tenths: number; p_liking: number }; Returns: Database['public']['Tables']['ratings']['Row'] };
      submit_rating_with_questions: { Args: { p_round_id: string; p_price_bucket: number; p_alcohol_tenths: number; p_liking: number; p_answers: Json }; Returns: Json };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
