import { expect, test } from '@playwright/test';

test('host → saját tipp → blokkos felfedés → végeredmény', async ({ page }, testInfo) => {
  await page.goto('/demo');
  await expect(page.getByRole('heading', { name: 'Helyi demó' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('host.png'), fullPage: true });
  await page.getByRole('button', { name: 'Kóstoló indítása' }).click();
  await page.getByRole('button', { name: 'Játékos', exact: true }).click();
  await page.getByRole('radio', { name: '4 001–6 000 Ft', exact: true }).check();
  await page.getByLabel('Becsült alkoholfok (% vol)').fill('12,5');
  await page.getByRole('radio', { name: 'Tetszés: 7 a 10-ből' }).check();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('player.png'), fullPage: true });
  await page.getByRole('button', { name: 'Tipp beküldése' }).click();
  await expect(page.getByRole('status')).toContainText('Tipp elmentve');
  await page.getByRole('button', { name: 'Prezentáció' }).click();
  await expect(page.getByText('Dűlőjáró · Furmint 2024')).toHaveCount(0);
  await page.getByRole('button', { name: 'Játékmester', exact: true }).click();
  await page.getByRole('button', { name: 'Kör lezárása' }).click();
  await expect(page.getByRole('button', { name: 'Eredmények felfedése' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Következő tétel' }).click();
  await page.getByRole('button', { name: 'Kör lezárása' }).click();
  await page.getByRole('button', { name: 'Eredmények felfedése' }).click();
  await page.getByRole('button', { name: 'Prezentáció' }).click();
  await expect(page.getByRole('heading', { name: 'Dűlőjáró · Furmint 2024' })).toBeVisible();
  await expect(page.locator('.score-summary')).toContainText('100');
  await page.getByRole('button', { name: 'Játékmester', exact: true }).click();
  await page.getByRole('button', { name: 'Következő tétel' }).click();
  await page.getByRole('button', { name: 'Kör lezárása' }).click();
  await page.getByRole('button', { name: 'Eredmények felfedése' }).click();
  await page.getByRole('button', { name: 'Kóstoló befejezése' }).click();
  await expect(page.locator('.score-summary')).toContainText('Végeredmény');
  await expect(page.getByRole('heading', { name: 'Nyári tétel · Rosé 2024' })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('results.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('lejárt időnél a játékos nem küldhet be és nem hosszabbítható a kör', async ({ page }) => {
  await page.clock.install();
  await page.goto('/demo');
  await page.getByLabel('Kóstolási idő').selectOption('60');
  await page.getByRole('button', { name: 'Kóstoló indítása' }).click();
  await page.getByRole('button', { name: 'Játékos', exact: true }).click();
  await page.clock.fastForward(61_000);
  await expect(page.getByRole('button', { name: 'Tipp beküldése' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Játékmester', exact: true }).click();
  await expect(page.getByRole('button', { name: '+30 másodperc' })).toBeDisabled();
});

test('helyi borfotó cseréje, hibája, törlése és felfedése', async ({ page }, testInfo) => {
  const photoRequests: string[] = [];
  page.on('request', request => { if (request.url().includes('/demo/sample-wine-')) photoRequests.push(request.url()); });
  await page.goto('/demo');
  await page.getByRole('button', { name: 'Játékos', exact: true }).click();
  await expect(page.locator('.wine-photo')).toHaveCount(0);
  expect(photoRequests).toEqual([]);
  await page.getByRole('button', { name: 'Játékmester', exact: true }).click();
  await page.getByText('Mintaborok képei', { exact: true }).click();
  const photo = page.locator('.demo-photo-row').first().locator('img');
  await expect(photo).toBeVisible();
  await page.getByLabel('Kép kiválasztása · 1. tétel').setInputFiles('public/demo/sample-wine-03.png');
  await expect(photo).toHaveAttribute('src', /^blob:/);
  const customSrc = await photo.getAttribute('src');
  await page.getByLabel('Kép kiválasztása · 1. tétel').setInputFiles({ name: 'broken.png', mimeType: 'image/png', buffer: Buffer.from('invalid image') });
  await expect(page.getByText('A kép nem olvasható. Válassz másik fájlt.')).toBeVisible();
  await expect(photo).toHaveAttribute('src', customSrc!);
  await page.getByLabel('Kép kiválasztása · 1. tétel').setInputFiles({ name: 'bad.txt', mimeType: 'text/plain', buffer: Buffer.from('invalid type') });
  await expect(page.getByText('JPEG, PNG vagy WebP képet válassz.')).toBeVisible();
  await page.getByLabel('Kép kiválasztása · 1. tétel').setInputFiles({ name: 'big.png', mimeType: 'image/png', buffer: Buffer.alloc(8 * 1024 * 1024 + 1) });
  await expect(page.getByText('Legfeljebb 8 MB-os képet válassz.')).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('photo-editor.png'), fullPage: true });
  await page.getByLabel('Felfedés gyakorisága').selectOption('1');
  await page.getByRole('button', { name: 'Kóstoló indítása' }).click();
  await page.getByRole('button', { name: 'Játékos', exact: true }).click();
  await expect(page.locator('.wine-photo')).toHaveCount(0);
  await page.getByRole('button', { name: 'Prezentáció' }).click();
  await expect(page.locator('.wine-photo')).toHaveCount(0);
  await page.getByRole('button', { name: 'Játékmester', exact: true }).click();
  await page.getByRole('button', { name: 'Kör lezárása' }).click();
  await page.getByRole('button', { name: 'Eredmények felfedése' }).click();
  await page.getByRole('button', { name: 'Prezentáció' }).click();
  await expect(page.locator('.result-card img')).toHaveAttribute('src', customSrc!);
  await page.getByRole('button', { name: 'Játékmester', exact: true }).click();
  await page.getByText('Mintaborok képei', { exact: true }).click();
  await page.getByRole('button', { name: 'Kép törlése · 1. tétel', exact: true }).click();
  await page.getByRole('button', { name: 'Prezentáció' }).click();
  await expect(page.locator('.result-card img')).toHaveCount(0);
  await expect(page.getByText('Kép nélküli mintabor')).toBeVisible();
  await page.getByRole('button', { name: 'Játékmester', exact: true }).click();
  await page.getByText('Mintaborok képei', { exact: true }).click();
  await page.getByRole('button', { name: 'Mintakép · 1. tétel', exact: true }).click();
  await expect(photo).toHaveAttribute('src', '/demo/sample-wine-01.png');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

test('időkorlát nélküli demó, kategóriaikonok és egyszerű tetszésszámok',async({page},info)=>{
  await page.clock.install();await page.goto('/demo');
  await page.getByRole('checkbox',{name:'Időkorlát használata'}).uncheck();
  await page.getByRole('button',{name:'Kóstoló indítása'}).click();
  await page.getByRole('button',{name:'Játékos',exact:true}).click();
  await page.clock.fastForward(3600000);
  await expect(page.getByRole('button',{name:'Tipp beküldése'})).toBeEnabled();
  await expect(page.locator('.rating-fields .rating-category-icon')).toHaveCount(3);
  await expect(page.locator('.rating-liking span')).toHaveText(['1','2','3','4','5','6','7','8','9','10']);
  await expect(page.locator('.rating-heading')).toContainText('Időkorlát nélkül');
  await page.screenshot({path:info.outputPath('demo-untimed.png'),fullPage:true});
  await page.getByRole('button',{name:'Játékmester',exact:true}).click();
  await page.getByRole('checkbox',{name:'Időkorlát használata'}).check();
  await page.getByRole('button',{name:'Játékos',exact:true}).click();
  await expect(page.locator('.timer')).toBeVisible();
  await page.getByRole('button',{name:'Játékmester',exact:true}).click();
  await page.getByRole('button',{name:'Kör lezárása',exact:false}).click();
  await page.getByRole('button',{name:'Játékos',exact:true}).click();
  await expect(page.getByRole('button',{name:'Tipp beküldése'})).toHaveCount(0);
});
